// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/mirror/mirror.proto

// The mirror service controls packet mirroring sessions.

package mirror

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRequest_TrafficType int32

const (
	StartRequest_TT_UNKNOWN StartRequest_TrafficType = 0
	// Only mirror MPLS traffic.
	StartRequest_TT_MPLS StartRequest_TrafficType = 1
	// Only mirror IP traffic.
	StartRequest_TT_IP StartRequest_TrafficType = 2
)

// Enum value maps for StartRequest_TrafficType.
var (
	StartRequest_TrafficType_name = map[int32]string{
		0: "TT_UNKNOWN",
		1: "TT_MPLS",
		2: "TT_IP",
	}
	StartRequest_TrafficType_value = map[string]int32{
		"TT_UNKNOWN": 0,
		"TT_MPLS":    1,
		"TT_IP":      2,
	}
)

func (x StartRequest_TrafficType) Enum() *StartRequest_TrafficType {
	p := new(StartRequest_TrafficType)
	*p = x
	return p
}

func (x StartRequest_TrafficType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartRequest_TrafficType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mirror_mirror_proto_enumTypes[0].Descriptor()
}

func (StartRequest_TrafficType) Type() protoreflect.EnumType {
	return &file_proto_mirror_mirror_proto_enumTypes[0]
}

func (x StartRequest_TrafficType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartRequest_TrafficType.Descriptor instead.
func (StartRequest_TrafficType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mirror_mirror_proto_rawDescGZIP(), []int{0, 0}
}

type StartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From        string                   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To          string                   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	TrafficType StartRequest_TrafficType `protobuf:"varint,3,opt,name=traffic_type,json=trafficType,proto3,enum=openconfig.magna.mirror.StartRequest_TrafficType" json:"traffic_type,omitempty"`
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mirror_mirror_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mirror_mirror_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_proto_mirror_mirror_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *StartRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *StartRequest) GetTrafficType() StartRequest_TrafficType {
	if x != nil {
		return x.TrafficType
	}
	return StartRequest_TT_UNKNOWN
}

type StartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mirror_mirror_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mirror_mirror_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_proto_mirror_mirror_proto_rawDescGZIP(), []int{1}
}

type StopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mirror_mirror_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mirror_mirror_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_mirror_mirror_proto_rawDescGZIP(), []int{2}
}

func (x *StopRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *StopRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mirror_mirror_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mirror_mirror_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_mirror_mirror_proto_rawDescGZIP(), []int{3}
}

var File_proto_mirror_mirror_proto protoreflect.FileDescriptor

var file_proto_mirror_mirror_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x2f, 0x6d,
	0x69, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x6f, 0x70, 0x65,
	0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x61, 0x2e, 0x6d, 0x69,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0xbf, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x54, 0x0a, 0x0c, 0x74, 0x72, 0x61,
	0x66, 0x66, 0x69, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x31, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x6d, 0x61, 0x67,
	0x6e, 0x61, 0x2e, 0x6d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x35, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x0a, 0x54, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x54, 0x54, 0x5f, 0x4d, 0x50, 0x4c, 0x53, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x54,
	0x54, 0x5f, 0x49, 0x50, 0x10, 0x02, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x31, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x74,
	0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb5, 0x01, 0x0a, 0x06, 0x4d,
	0x69, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x56, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x25,
	0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x6d, 0x61, 0x67, 0x6e,
	0x61, 0x2e, 0x6d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x61, 0x2e, 0x6d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a,
	0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x24, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x61, 0x2e, 0x6d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x2e,
	0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x61, 0x2e, 0x6d,
	0x69, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x6d, 0x61, 0x67, 0x6e,
	0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mirror_mirror_proto_rawDescOnce sync.Once
	file_proto_mirror_mirror_proto_rawDescData = file_proto_mirror_mirror_proto_rawDesc
)

func file_proto_mirror_mirror_proto_rawDescGZIP() []byte {
	file_proto_mirror_mirror_proto_rawDescOnce.Do(func() {
		file_proto_mirror_mirror_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mirror_mirror_proto_rawDescData)
	})
	return file_proto_mirror_mirror_proto_rawDescData
}

var file_proto_mirror_mirror_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_mirror_mirror_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_mirror_mirror_proto_goTypes = []interface{}{
	(StartRequest_TrafficType)(0), // 0: openconfig.magna.mirror.StartRequest.TrafficType
	(*StartRequest)(nil),          // 1: openconfig.magna.mirror.StartRequest
	(*StartResponse)(nil),         // 2: openconfig.magna.mirror.StartResponse
	(*StopRequest)(nil),           // 3: openconfig.magna.mirror.StopRequest
	(*StopResponse)(nil),          // 4: openconfig.magna.mirror.StopResponse
}
var file_proto_mirror_mirror_proto_depIdxs = []int32{
	0, // 0: openconfig.magna.mirror.StartRequest.traffic_type:type_name -> openconfig.magna.mirror.StartRequest.TrafficType
	1, // 1: openconfig.magna.mirror.Mirror.Start:input_type -> openconfig.magna.mirror.StartRequest
	3, // 2: openconfig.magna.mirror.Mirror.Stop:input_type -> openconfig.magna.mirror.StopRequest
	2, // 3: openconfig.magna.mirror.Mirror.Start:output_type -> openconfig.magna.mirror.StartResponse
	4, // 4: openconfig.magna.mirror.Mirror.Stop:output_type -> openconfig.magna.mirror.StopResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_mirror_mirror_proto_init() }
func file_proto_mirror_mirror_proto_init() {
	if File_proto_mirror_mirror_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mirror_mirror_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mirror_mirror_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mirror_mirror_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mirror_mirror_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mirror_mirror_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mirror_mirror_proto_goTypes,
		DependencyIndexes: file_proto_mirror_mirror_proto_depIdxs,
		EnumInfos:         file_proto_mirror_mirror_proto_enumTypes,
		MessageInfos:      file_proto_mirror_mirror_proto_msgTypes,
	}.Build()
	File_proto_mirror_mirror_proto = out.File
	file_proto_mirror_mirror_proto_rawDesc = nil
	file_proto_mirror_mirror_proto_goTypes = nil
	file_proto_mirror_mirror_proto_depIdxs = nil
}
